[programs.localnet]
mysolanaapp = "6KAAhZbFDFKLv9Nxwg1mHRRMcGZ62BXECh6bnqZdpT2N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/cryptopragmatic/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
